class PARAMS_CODES {
  static PARAMS_TIPO_CUENTA = "TIPO_CUENTA";
  static PARAMS_TIPO_CONSUMIDOR = "TIPO_CONSUMIDOR";
  static PARAMS_TIPO_SERVICIO = "TIPO_SERVICIO";
  static PARAMS_TIPO_PAGO = "TIPO_PAGO";
  static PARAMS_TIPO_CLIENTE = "TIPO_CLIENTE";
}

export default PARAMS_CODES